# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alumno.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alumno(object):
    def setupUi(self, alumno):
        alumno.setObjectName("alumno")
        alumno.resize(590, 524)
        self.centralwidget = QtWidgets.QWidget(alumno)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 180, 161, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 230, 161, 16))
        self.label_5.setObjectName("label_5")
        self.txt_id = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_id.setGeometry(QtCore.QRect(260, 100, 113, 20))
        self.txt_id.setObjectName("txt_id")
        self.txt_nom = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nom.setGeometry(QtCore.QRect(260, 140, 113, 20))
        self.txt_nom.setObjectName("txt_nom")
        self.txt_ape = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_ape.setGeometry(QtCore.QRect(260, 180, 113, 20))
        self.txt_ape.setObjectName("txt_ape")
        self.txt_dni = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_dni.setGeometry(QtCore.QRect(260, 220, 113, 20))
        self.txt_dni.setObjectName("txt_dni")
        self.tb_listar = QtWidgets.QTableView(self.centralwidget)
        self.tb_listar.setGeometry(QtCore.QRect(50, 270, 481, 192))
        self.tb_listar.setObjectName("tb_listar")
        self.btn_ingresar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ingresar.setGeometry(QtCore.QRect(450, 100, 111, 41))
        self.btn_ingresar.setObjectName("btn_ingresar")
        self.btn_retornar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_retornar.setGeometry(QtCore.QRect(470, 190, 75, 23))
        self.btn_retornar.setObjectName("btn_retornar")
        alumno.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(alumno)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 21))
        self.menubar.setObjectName("menubar")
        alumno.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(alumno)
        self.statusbar.setObjectName("statusbar")
        alumno.setStatusBar(self.statusbar)

        self.retranslateUi(alumno)
        QtCore.QMetaObject.connectSlotsByName(alumno)

    def retranslateUi(self, alumno):
        _translate = QtCore.QCoreApplication.translate
        alumno.setWindowTitle(_translate("alumno", "MainWindow"))
        self.label.setText(_translate("alumno", "BIENVENIDO AL MENU DE ALUMNOS"))
        self.label_2.setText(_translate("alumno", "INGRESE EL ID DEL ALUMNO :"))
        self.label_3.setText(_translate("alumno", "INGRESE EL NOMBRE :"))
        self.label_4.setText(_translate("alumno", "INGRESE APELLIDO : "))
        self.label_5.setText(_translate("alumno", "INGRESE EL DNI DEL ALUMNO : "))
        self.btn_ingresar.setText(_translate("alumno", "INGRESAR ALUMNO "))
        self.btn_retornar.setText(_translate("alumno", "RETORNAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    alumno = QtWidgets.QMainWindow()
    ui = Ui_alumno()
    ui.setupUi(alumno)
    alumno.show()
    sys.exit(app.exec_())
