# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instructor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_instrutor(object):
    def setupUi(self, instrutor):
        instrutor.setObjectName("instrutor")
        instrutor.resize(576, 600)
        self.centralwidget = QtWidgets.QWidget(instrutor)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 191, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 201, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 220, 161, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 180, 211, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 260, 161, 16))
        self.label_6.setObjectName("label_6")
        self.btn_retornar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_retornar.setGeometry(QtCore.QRect(440, 320, 101, 23))
        self.btn_retornar.setObjectName("btn_retornar")
        self.btn_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_registrar.setGeometry(QtCore.QRect(440, 370, 101, 23))
        self.btn_registrar.setObjectName("btn_registrar")
        self.btn_listar = QtWidgets.QTableView(self.centralwidget)
        self.btn_listar.setGeometry(QtCore.QRect(50, 300, 371, 192))
        self.btn_listar.setObjectName("btn_listar")
        self.txt_id = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_id.setGeometry(QtCore.QRect(282, 100, 181, 20))
        self.txt_id.setObjectName("txt_id")
        self.txt_nom = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nom.setGeometry(QtCore.QRect(280, 140, 181, 20))
        self.txt_nom.setObjectName("txt_nom")
        self.txt_car = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_car.setGeometry(QtCore.QRect(280, 220, 181, 20))
        self.txt_car.setObjectName("txt_car")
        self.txt_gmail = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_gmail.setGeometry(QtCore.QRect(280, 260, 181, 20))
        self.txt_gmail.setObjectName("txt_gmail")
        self.txt_ape = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_ape.setGeometry(QtCore.QRect(280, 180, 181, 20))
        self.txt_ape.setObjectName("txt_ape")
        instrutor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(instrutor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 21))
        self.menubar.setObjectName("menubar")
        instrutor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(instrutor)
        self.statusbar.setObjectName("statusbar")
        instrutor.setStatusBar(self.statusbar)

        self.retranslateUi(instrutor)
        QtCore.QMetaObject.connectSlotsByName(instrutor)

    def retranslateUi(self, instrutor):
        _translate = QtCore.QCoreApplication.translate
        instrutor.setWindowTitle(_translate("instrutor", "MainWindow"))
        self.label.setText(_translate("instrutor", "BIENVENIDO AL MENU DE INSTRUCTORES"))
        self.label_2.setText(_translate("instrutor", "INGRESE EL ID DEL INSTRUCTOR :"))
        self.label_3.setText(_translate("instrutor", "INGRESE EL NOMBRE DEL INSTRUCTOR :"))
        self.label_4.setText(_translate("instrutor", "INGRESE EL AULA A CARGO :"))
        self.label_5.setText(_translate("instrutor", "INGRESE EL APELLIDO DEL INSTRUCTOR :"))
        self.label_6.setText(_translate("instrutor", "INGRESE EL CORREO :"))
        self.btn_retornar.setText(_translate("instrutor", "RETORNAR"))
        self.btn_registrar.setText(_translate("instrutor", "REGISTRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    instrutor = QtWidgets.QMainWindow()
    ui = Ui_instrutor()
    ui.setupUi(instrutor)
    instrutor.show()
    sys.exit(app.exec_())
