# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(550, 261)
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 italic 25pt \"Bahnschrift\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 311, 16))
        self.label_2.setObjectName("label_2")
        self.btn_alumno = QtWidgets.QPushButton(self.centralwidget)
        self.btn_alumno.setGeometry(QtCore.QRect(120, 140, 75, 23))
        self.btn_alumno.setObjectName("btn_alumno")
        self.btn_instructor = QtWidgets.QPushButton(self.centralwidget)
        self.btn_instructor.setGeometry(QtCore.QRect(270, 140, 101, 23))
        self.btn_instructor.setObjectName("btn_instructor")
        Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Menu)
        self.statusbar.setObjectName("statusbar")
        Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "MainWindow"))
        self.label.setText(_translate("Menu", "BIENVENIDO AL MENU  DEL SISTEMA "))
        self.label_2.setText(_translate("Menu", "A DONDE QUIERE IR? PUEDE ELIGIR LAS SIGUESTES OPCINES :"))
        self.btn_alumno.setText(_translate("Menu", "ALUMNOS"))
        self.btn_instructor.setText(_translate("Menu", "INSTRUCTORES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QMainWindow()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
